apiVersion: v1
kind: ConfigMap
metadata:
  name: champion-config
  namespace: champion
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
  CLICKHOUSE_HOST: "clickhouse-service"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: "champion_market"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  PREFECT_API_URL: "http://prefect-service:4200/api"
