apiVersion: v1
kind: Secret
metadata:
  name: champion-secrets
  namespace: champion
type: Opaque
stringData:
  CLICKHOUSE_USER: "champion_user"
  CLICKHOUSE_PASSWORD: "champion_pass"
  GF_SECURITY_ADMIN_PASSWORD: "admin"
